#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StyleLights.Resource", IsApplication=true)]

namespace StyleLights
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int color_array = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int lighting_array = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int mock_device_data_array = 2131034114;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hoodie_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int hoodie_front = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070047
			public const int AccountSettingsButton = 2131165255;
			
			// aapt resource value: 0x7f07004d
			public const int ActivateButton = 2131165261;
			
			// aapt resource value: 0x7f070042
			public const int CommunityButton = 2131165250;
			
			// aapt resource value: 0x7f070049
			public const int ContactButton = 2131165257;
			
			// aapt resource value: 0x7f070046
			public const int CreateNewButton = 2131165254;
			
			// aapt resource value: 0x7f070045
			public const int CustomButton = 2131165253;
			
			// aapt resource value: 0x7f070041
			public const int CustomizeButton = 2131165249;
			
			// aapt resource value: 0x7f070039
			public const int DevicesButton = 2131165241;
			
			// aapt resource value: 0x7f070048
			public const int NotificationSettingsButton = 2131165256;
			
			// aapt resource value: 0x7f070053
			public const int Preset1Button = 2131165267;
			
			// aapt resource value: 0x7f070044
			public const int PresetsButton = 2131165252;
			
			// aapt resource value: 0x7f07003a
			public const int ScanButton = 2131165242;
			
			// aapt resource value: 0x7f070040
			public const int SelectionButton = 2131165248;
			
			// aapt resource value: 0x7f070043
			public const int SettingsButton = 2131165251;
			
			// aapt resource value: 0x7f07000a
			public const int arms = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int back = 2131165195;
			
			// aapt resource value: 0x7f070026
			public const int blueText = 2131165222;
			
			// aapt resource value: 0x7f070030
			public const int brightness = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int brightnessSlider = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int brightnessVal = 2131165234;
			
			// aapt resource value: 0x7f070012
			public const int button1 = 2131165202;
			
			// aapt resource value: 0x7f070054
			public const int button2 = 2131165268;
			
			// aapt resource value: 0x7f070058
			public const int button3 = 2131165272;
			
			// aapt resource value: 0x7f070003
			public const int button5 = 2131165187;
			
			// aapt resource value: 0x7f07002f
			public const int button6 = 2131165231;
			
			// aapt resource value: 0x7f070009
			public const int chest = 2131165193;
			
			// aapt resource value: 0x7f07001e
			public const int color1 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int color2 = 2131165215;
			
			// aapt resource value: 0x7f070016
			public const int colorButton = 2131165206;
			
			// aapt resource value: 0x7f07001a
			public const int colorSpinner = 2131165210;
			
			// aapt resource value: 0x7f07002c
			public const int customize = 2131165228;
			
			// aapt resource value: 0x7f070035
			public const int duration = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int editText3 = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int editText4 = 2131165239;
			
			// aapt resource value: 0x7f070033
			public const int effect = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int effectSpinner = 2131165236;
			
			// aapt resource value: 0x7f070028
			public const int greenText = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int hueText = 2131165225;
			
			// aapt resource value: 0x7f07004e
			public const int imageView1 = 2131165262;
			
			// aapt resource value: 0x7f070015
			public const int lightingButton = 2131165205;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout12 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int linearLayout13 = 2131165208;
			
			// aapt resource value: 0x7f070020
			public const int linearLayout14 = 2131165216;
			
			// aapt resource value: 0x7f070011
			public const int linearLayout16 = 2131165201;
			
			// aapt resource value: 0x7f070006
			public const int linearLayout17 = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout18 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int linearLayout19 = 2131165197;
			
			// aapt resource value: 0x7f07003c
			public const int linearLayout2 = 2131165244;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout20 = 2131165185;
			
			// aapt resource value: 0x7f070014
			public const int linearLayout21 = 2131165204;
			
			// aapt resource value: 0x7f07001b
			public const int linearLayout22 = 2131165211;
			
			// aapt resource value: 0x7f070021
			public const int linearLayout23 = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int linearLayout25 = 2131165218;
			
			// aapt resource value: 0x7f07003e
			public const int linearLayout3 = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int linearLayout5 = 2131165247;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout6 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout7 = 2131165189;
			
			// aapt resource value: 0x7f070050
			public const int linearLayoutCstmSlct1 = 2131165264;
			
			// aapt resource value: 0x7f07004f
			public const int linearLayoutCstmSlctn2 = 2131165263;
			
			// aapt resource value: 0x7f070056
			public const int linearLayoutPrst1 = 2131165270;
			
			// aapt resource value: 0x7f070055
			public const int linearLayoutPrst2 = 2131165269;
			
			// aapt resource value: 0x7f07004c
			public const int linearLayoutPtrnActvt1 = 2131165260;
			
			// aapt resource value: 0x7f07004b
			public const int linearLayoutPtrnActvt2 = 2131165259;
			
			// aapt resource value: 0x7f07004a
			public const int linearLayoutPtrnActvt3 = 2131165258;
			
			// aapt resource value: 0x7f070024
			public const int redText = 2131165220;
			
			// aapt resource value: 0x7f070007
			public const int region = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int regiongroup = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int reset = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int rotate = 2131165199;
			
			// aapt resource value: 0x7f07002a
			public const int satText = 2131165226;
			
			// aapt resource value: 0x7f070013
			public const int saveButton = 2131165203;
			
			// aapt resource value: 0x7f070002
			public const int selectionButton = 2131165186;
			
			// aapt resource value: 0x7f07002e
			public const int settings = 2131165230;
			
			// aapt resource value: 0x7f07002d
			public const int share = 2131165229;
			
			// aapt resource value: 0x7f070010
			public const int shirt = 2131165200;
			
			// aapt resource value: 0x7f070052
			public const int tableRow1 = 2131165266;
			
			// aapt resource value: 0x7f07003b
			public const int textView1 = 2131165243;
			
			// aapt resource value: 0x7f070019
			public const int textView2 = 2131165209;
			
			// aapt resource value: 0x7f07001c
			public const int textView3 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int textView4 = 2131165213;
			
			// aapt resource value: 0x7f070023
			public const int textView5 = 2131165219;
			
			// aapt resource value: 0x7f070025
			public const int textView6 = 2131165221;
			
			// aapt resource value: 0x7f070027
			public const int textView7 = 2131165223;
			
			// aapt resource value: 0x7f070038
			public const int textView8 = 2131165240;
			
			// aapt resource value: 0x7f070051
			public const int textViewCustom = 2131165265;
			
			// aapt resource value: 0x7f070057
			public const int textViewPreset = 2131165271;
			
			// aapt resource value: 0x7f07003d
			public const int toggleButton1 = 2131165245;
			
			// aapt resource value: 0x7f07002b
			public const int valText = 2131165227;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomizeColor = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomizeLighting = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DevicesScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainSelectionScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainSettingsScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int NavigationBar = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PatternActivateScreen = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PatternSelectionScreenCustom = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int PatternSelectionScreenPresets = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int colorEffectSpinner = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int lightingPatternSpinner = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
