#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("StyleLights.Resource", IsApplication=true)]

namespace StyleLights
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int mock_device_data_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060043
			public const int AccountSettingsButton = 2131099715;
			
			// aapt resource value: 0x7f060049
			public const int ActivateButton = 2131099721;
			
			// aapt resource value: 0x7f06003e
			public const int CommunityButton = 2131099710;
			
			// aapt resource value: 0x7f060045
			public const int ContactButton = 2131099717;
			
			// aapt resource value: 0x7f060042
			public const int CreateNewButton = 2131099714;
			
			// aapt resource value: 0x7f060041
			public const int CustomButton = 2131099713;
			
			// aapt resource value: 0x7f06003d
			public const int CustomizeButton = 2131099709;
			
			// aapt resource value: 0x7f060036
			public const int DevicesButton = 2131099702;
			
			// aapt resource value: 0x7f060044
			public const int NotificationSettingsButton = 2131099716;
			
			// aapt resource value: 0x7f06004e
			public const int Preset1Button = 2131099726;
			
			// aapt resource value: 0x7f060040
			public const int PresetsButton = 2131099712;
			
			// aapt resource value: 0x7f060037
			public const int ScanButton = 2131099703;
			
			// aapt resource value: 0x7f06003c
			public const int SelectionButton = 2131099708;
			
			// aapt resource value: 0x7f06003f
			public const int SettingsButton = 2131099711;
			
			// aapt resource value: 0x7f060024
			public const int arms = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int back = 2131099685;
			
			// aapt resource value: 0x7f06002a
			public const int brightness = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int brightnessSlider = 2131099691;
			
			// aapt resource value: 0x7f060010
			public const int button1 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int button2 = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int button3 = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int button4 = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int button5 = 2131099650;
			
			// aapt resource value: 0x7f060013
			public const int button6 = 2131099667;
			
			// aapt resource value: 0x7f06001a
			public const int button7 = 2131099674;
			
			// aapt resource value: 0x7f060023
			public const int chest = 2131099683;
			
			// aapt resource value: 0x7f06001d
			public const int customize = 2131099677;
			
			// aapt resource value: 0x7f06002e
			public const int duration = 2131099694;
			
			// aapt resource value: 0x7f060031
			public const int editText3 = 2131099697;
			
			// aapt resource value: 0x7f060034
			public const int editText4 = 2131099700;
			
			// aapt resource value: 0x7f06002c
			public const int effect = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int effectSpinner = 2131099693;
			
			// aapt resource value: 0x7f06000d
			public const int imageButton1 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int imageView1 = 2131099662;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060014
			public const int linearLayout12 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int linearLayout13 = 2131099669;
			
			// aapt resource value: 0x7f06001b
			public const int linearLayout14 = 2131099675;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout15 = 2131099653;
			
			// aapt resource value: 0x7f06000f
			public const int linearLayout16 = 2131099663;
			
			// aapt resource value: 0x7f060007
			public const int linearLayout17 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout18 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout19 = 2131099659;
			
			// aapt resource value: 0x7f060038
			public const int linearLayout2 = 2131099704;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout20 = 2131099649;
			
			// aapt resource value: 0x7f060012
			public const int linearLayout21 = 2131099666;
			
			// aapt resource value: 0x7f06003a
			public const int linearLayout3 = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int linearLayout5 = 2131099707;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout6 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout7 = 2131099652;
			
			// aapt resource value: 0x7f06004b
			public const int linearLayoutCstmSlct1 = 2131099723;
			
			// aapt resource value: 0x7f06004a
			public const int linearLayoutCstmSlctn2 = 2131099722;
			
			// aapt resource value: 0x7f060050
			public const int linearLayoutPrst1 = 2131099728;
			
			// aapt resource value: 0x7f06004f
			public const int linearLayoutPrst2 = 2131099727;
			
			// aapt resource value: 0x7f060048
			public const int linearLayoutPtrnActvt1 = 2131099720;
			
			// aapt resource value: 0x7f060047
			public const int linearLayoutPtrnActvt2 = 2131099719;
			
			// aapt resource value: 0x7f060046
			public const int linearLayoutPtrnActvt3 = 2131099718;
			
			// aapt resource value: 0x7f060009
			public const int radioButton1 = 2131099657;
			
			// aapt resource value: 0x7f060021
			public const int redo = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int region = 2131099682;
			
			// aapt resource value: 0x7f060027
			public const int reset = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int rotate = 2131099688;
			
			// aapt resource value: 0x7f06001c
			public const int select = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int settings = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int share = 2131099678;
			
			// aapt resource value: 0x7f060029
			public const int shirt = 2131099689;
			
			// aapt resource value: 0x7f060026
			public const int single = 2131099686;
			
			// aapt resource value: 0x7f060017
			public const int spinner1 = 2131099671;
			
			// aapt resource value: 0x7f06002f
			public const int spinner2 = 2131099695;
			
			// aapt resource value: 0x7f06004d
			public const int tableRow1 = 2131099725;
			
			// aapt resource value: 0x7f060008
			public const int textView1 = 2131099656;
			
			// aapt resource value: 0x7f060016
			public const int textView2 = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int textView3 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int textView4 = 2131099673;
			
			// aapt resource value: 0x7f060030
			public const int textView5 = 2131099696;
			
			// aapt resource value: 0x7f060032
			public const int textView6 = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int textView7 = 2131099699;
			
			// aapt resource value: 0x7f060035
			public const int textView8 = 2131099701;
			
			// aapt resource value: 0x7f06004c
			public const int textViewCustom = 2131099724;
			
			// aapt resource value: 0x7f060051
			public const int textViewPreset = 2131099729;
			
			// aapt resource value: 0x7f060039
			public const int toggleButton1 = 2131099705;
			
			// aapt resource value: 0x7f060020
			public const int undo = 2131099680;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomizeColor = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomizeLighting = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DevicesScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainSelectionScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainSettingsScreen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PatternActivateScreen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PatternSelectionScreenCustom = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int PatternSelectionScreenPresets = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
